'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),{create}=require('../public/client-connection');
function harness(){const sockets=[],timers=new Map(),received=[],closed=[];let id=0;
 class Socket{constructor(){this.readyState=0;this.events={};this.sent=[];sockets.push(this);}addEventListener(n,f){this.events[n]=f;}emit(n,e={}){if(n==='open')this.readyState=1;if(n==='close')this.readyState=3;this.events[n]?.(e);}send(s){this.sent.push(JSON.parse(s));}close(){this.readyState=3;}message(type){this.emit('message',{data:JSON.stringify({type})});}}
 const link=create({url:()=>'',WebSocket:Socket,setTimeout:(f,ms)=>{timers.set(++id,{f,ms});return id;},clearTimeout:id=>timers.delete(id),onSocket(){},onOpen(){},onMessage:m=>received.push(m),onDisconnect:e=>closed.push(e)});
 const fire=ms=>{const entry=[...timers].find(([,v])=>v.ms===ms);assert.ok(entry,`timer ${ms}`);timers.delete(entry[0]);entry[1].f();};return {link,sockets,timers,received,closed,fire};}
test('replacement stops reconnect ping-pong, including foreground resume',()=>{const h=harness();h.link.connect();const s=h.sockets[0];s.emit('open');s.message('replaced');s.emit('close',{code:4000});h.link.resume();h.link.connect();assert.equal(h.sockets.length,1);assert.equal(h.timers.size,0);assert.equal(h.closed.length,1);});
test('one reconnect timer and one socket; events from abandoned sockets cannot replace current state',()=>{const h=harness();h.link.connect();h.link.connect();assert.equal(h.sockets.length,1);const old=h.sockets[0];old.emit('close');old.emit('close');h.fire(500);h.sockets[1].emit('open');old.message('replaced');old.emit('close');assert.equal(h.closed.length,1);assert.equal(h.received.length,0);h.link.resume();assert.equal(h.sockets.length,2);});
test('unresponsive connection is replaced, responsive pong cancels the deadline',()=>{const h=harness();h.link.connect();h.sockets[0].emit('open');h.link.resume();assert.equal(h.sockets[0].sent[0].type,'ping');h.sockets[0].message('pong');assert.equal([...h.timers.values()].some(v=>v.ms===8000),false);h.link.resume();h.fire(8000);h.fire(500);assert.equal(h.sockets.length,2);});
test('replacement close without message also stops reconnect',()=>{const h=harness();h.link.connect();h.sockets[0].emit('close',{code:4000});h.link.resume();assert.equal(h.sockets.length,1);assert.equal(h.timers.size,0);});
